syntax = "proto3";

package raptor.v1;

import "raptor/v1/battery.proto";
import "raptor/v1/env.proto";
import "raptor/v1/relay.proto";
import "raptor/v1/system.proto";

enum CommandStatus {
  COMMAND_STATUS_UNSPECIFIED = 0;
  COMMAND_STATUS_OK = 1;
  COMMAND_STATUS_GEN_ERR = 2;
  COMMAND_STATUS_UNKNOWN_COMMAND_ERR = 3;
  COMMAND_STATUS_DECODE_ERR = 4;
}

message DiscoveryRequest {}

message DiscoveryResponse {
  SystemMetadata metadata = 1;
}

message GetVersionRequest {}

message GetVersionResponse {
  string firmware_version = 1;
  string hardware_version = 2;
}

message GetAliveDataRequest {}

message GetAliveDataResponse {
  SystemStatus status = 1;
  Relays relays = 2;
  EnvironmentMeasurements env = 3;
  BatteryMeasurements battery = 4;
}

enum StreamControl {
  STREAM_CONTROL_UNSPECIFIED = 0;
  STREAM_CONTROL_START = 1;
  STREAM_CONTROL_SYNC = 2;
  STREAM_CONTROL_STOP = 3;
}

message StreamControlRequest {
  StreamControl control = 1;
}

message StreamControlResponse {
  uint32 sync_timestamp = 1;
}

message CommandRequest {
  int32 uuid = 1;
  oneof request_mux {
    DiscoveryRequest discovery = 2;
    GetVersionRequest get_version = 3;
    GetAliveDataRequest get_alive_data = 4;
    StreamControlRequest stream_control = 5;
  }
}

message CommandResponse {
  CommandStatus status = 1;
  oneof response_mux {
    DiscoveryResponse discovery = 2;
    GetVersionResponse get_version = 3;
    GetAliveDataResponse get_alive_data = 4;
    StreamControlResponse stream_control = 5;
  }
}
