syntax = "proto3";

package raptor.v1;

import "raptor/v1/battery.proto";
import "raptor/v1/env.proto";
import "raptor/v1/relay.proto";

// Version follows SemVer: https://semver.org
message Version {
  // semver major release
  uint32 major = 1;
  // semver minor release
  uint32 minor = 2;
  // semver patch release number
  uint32 patch = 3;
  // version control SHA1 hash (where applicable)
  string commit_sha = 4;
  // true if release candidate; false otherwise
  bool release_candidate = 5;
}

// device status states
enum DeviceStatus {
  // reserved
  DEVICE_STATUS_UNSPECIFIED = 0;

  DEVICE_STATUS_IDLE = 1;
  DEVICE_STATUS_CHARGING = 2;
  DEVICE_STATUS_ARMED = 3;
  DEVICE_STATUS_ACTIVE = 4;
  DEVICE_STATUS_IN_ERROR = 5;
  DEVICE_STATUS_SELF_TEST = 6;
}

message DeviceMetadata {
  // system universal unique identifer
  int32 uuid = 1;
  // device firmware version in semver format
  Version firmware_version = 2;
  // device hardware version in semver format
  Version hardware_version = 3;
  // true if device is a digital twin; false otherwise
  bool digital_twin = 4;
}

message DeviceAliveTelemetry {
  // device status
  DeviceStatus status = 1;
  // relay telemetry
  RelayTelemetry relays = 2;
  // environment telemetry
  EnvironmentTelemetry env = 3;
  // battery telemetry
  BatteryTelemetry battery = 4;
}

/***************** Device API *****************/

message DeviceMetadataRequest {}

message DeviceMetadataResponse {
  DeviceMetadata device = 1;
}

message DeviceAliveTelemetryRequest {}

message DeviceAliveTelemetryResponse {
  DeviceAliveTelemetry alive = 1;
}

message DeviceResetRequest {}

message DeviceResetResponse {}

message DeviceEstopRequest {}

message DeviceEstopResponse {}
