---
name: protocols
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    name: protobuf compile (nanopb)
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

  static_analysis:
    name: protobuf static analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup buf environment
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - name: run buf lint
        run: buf lint
      - name: run buf format
        run: buf format -d --exit-code
      - name: run buf breaking change detection against master
        run: buf breaking --against ${{ github.server_url }}/${{ github.repository }}.git#branch=master

