---
name: protocols
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "docs/**"
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  build:
    name: protobuf compile (nanopb)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  lint:
    name: protobuf lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          input: "protobuf"
          lint: ${{ github.event_name == 'push' }}


