---
name: protobuf ci 
on:
  push:
    paths:
      - '**.proto'
      - '**.options'
      - '**/buf.yaml'
      - '**/buf.lock'
      - '**/buf.md'
      - '**/README.md'
      - '**/LICENSE'
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  static-analysis:
    name: protobuf static analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup buf environment
        uses: bufbuild/buf-action@v1
        with:
          breaking_against: "${{ github.server_url }}/${{ github.repository }}.git#branch=master,ref=HEAD~1"
          lint: true
          format: true
          breaking: true
  build:
    name: protobuf code generation
    runs-on: ubuntu-latest
    needs: static-analysis
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup buf environment
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true
      - run: buf generate
      - name: archive autogen code 
        uses: actions/upload-artifact@v4
        with:
          name: raptor_pb
          path: gen
          retention-days: 5
