---
name: protobuf 
on:
  push:
    paths:
      - '**.proto'
      - '**.options'
      - '**/buf.yaml'
      - '**/buf.lock'
      - '**/buf.md'
      - '**/README.md'
      - '**/LICENSE'
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    name: protobuf compile (nanopb)
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
  protobuf_static_analysis:
    name: protobuf static analysis
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4
      - name: setup buf environment
        uses: bufbuild/buf-action@v1
        with:
          breaking-against: "${{ github.server_url }}/${{ github.repository }}.git#branch=master,ref=HEAD~1"
          lint: ${{ github.event_name == 'push' }}
          format: ${{ github.event_name == 'push' }}
          breaking: ${{ github.event_name == 'push' }}